### ISSUE TITLE
Extreme lag when opening any backpack

### ISSUE THREAD

**Issue by DragoSavitarY** [Stein-N/Resource-Backpacks#12]
Like the title says, everytime I open a backpack my FPS drops depending in the backpack, from the smallest container size (leather) my frames drop from 500 to 100-150 and with the netherite backpack it drops to 30-60. At first I thought it was another mod so I emptied my folder except for the resource backpack/config/lib mods and fabric api but still had the same issue. Its only with this mod and not with any other chest/backpack mods or normal minecraft chests.

Extra info: Minecraft Java 1.21.1, Mod v0.7.6-BETA

**Comment by Stein-N** [comment]
Hey i'm aware that there are frame drops, because of how the backpack Inventory is rendered currently.
Did you change the size of the Backpack Inventories, because with the default settings the frame drops for me are only ~10% with roughly 5 year old hardware(without sodium).

I notice a drastic fps drop like yours when the backpack exceeded ~300 slots.

But this will be adressed with the full release, because there will be a maximum size or eventually fixed sizes for the Backpack Inventories. But sadly i cant give an ETA for that.

**Comment by DragoSavitarY** [comment]
Hello, I indeed changed the sizes because I wanted them to match the chest inventory size of another mod I'm using (reinforced chests by Aton-Kish). Below is my current config file (max backpack slots being 162 for netherite). My pc has a 3060TI and a ryzen 3600 and even with sodium I still get the same fps drop. 

I really like the ability to change the sizes in the config so I'd love for you to keep it :)
I'll just wait for the update whenever it drops. Thank you for the great mod and quick response!


> ["Leather Backpack"]
> 	rows = 3
> 	columns = 9
> ["Copper Backpack"]
> 	rows = 5
> 	columns = 9
> ["Gold Backpack"]
> 	rows = 7
> 	columns = 9
> ["Iron Backpack"]
> 	rows = 9
> 	columns = 9
> ["Diamond Backpack"]
> 	rows = 9
> 	columns = 12
> ["Netherite Backpack"]
> 	rows = 9
> 	columns = 18

**Comment by Stein-N** [comment]
Ok gpu side it shouldn't be a problem and CPU is the same as mine.

I think it is really the problem with my current approach to render the inventory.

**Comment by DragoSavitarY** [comment]
After a LOT of testing I found out a big issue that causes all gui/interfaces to drop fps to around/below 60.

Recipe mods like NEI/REI/JEI cause fps to drop to 60 regardless of what gui u open (vanilla or modded). 
Disabling that mod makes all gui have normal fps and increases fps of resource_backpacks by 10, 
so now my fps is 40 instead of 30. 

Hope this helps somehow and good luck with your new render approach!

**Comment by Stein-N** [comment]
with version 0.9.0-BETA the rendering is redone, on my system there are no longer fps drops, when we talk about 'normal' fps values like 144fps.

With uncapped fps i still drop from ~1000 to ~600 and with EMI/REI/JEI down to ~300, but this is an issue from Minecraft itself or maybe Java, because when there is a high amount of Items being rendered fps drop like crazy
